name: "amairo_data"
version: "1.0.0"

profile: "amairo_data"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  amairo_data:
    +dbt-osmosis: "{model}.yml"
    staging:
      +materialized: view

flags:
  send_anonymous_usage_stats: false
