[project]
name = "amairo-data-platform"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["dbt-duckdb>=1.9.0", "shandy-sqlfmt[jinjafmt]>=0.23.2"]

[tool.uv]
dev-dependencies = ["ruff>=0.7.1"]
