[project]
name = "amairo-data-platform"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = ["dbt-duckdb>=1.9.0", "shandy-sqlfmt[jinjafmt]>=0.23.2"]

[tool.uv]
dev-dependencies = ["dbt-osmosis>=0.13.2", "ruff>=0.7.1"]
